# Site settings
title: Nipun Gunawardena
email: 1.nipun@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Multidisciplinary engineer looking to make a difference
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.madvoid.github.io" # the base hostname & protocol for your site
twitter_username: NipunUG
github_username: madvoid
# linkedin_username: nipgun

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
# job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# Template: https://github.com/svmiller/steve-ngvb-jekyll-template

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
